### ISSUE TITLE
[ios] Heroku app is down

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1567]
**Describe the bug**
https://keyman-ios-beta.herokuapp.com/ and
https://keyman-ios-alpha.herokuapp.com/

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by mcdurdin** [comment]
Resolved -- Apple account was locked.

**Comment by MayuraVerma** [comment]
This is still not resolved. We are not getting email after registration.
Previously registered emails are not accepted!
Please review this.

**Comment by mcdurdin** [comment]
@MayuraVerma We are looking at this further. Can you send me privately (e.g. DM on https://community.software.sil.org/) the email address you are registering with?

I note that there are currently no active iOS betas or alphas due to an upload issue. Investigating that as well.

**Comment by mcdurdin** [comment]
> I note that there are currently no active iOS betas or alphas due to an upload issue. Investigating that as well.

I have manually submitted build 11.0.300 for review. Once it passes App Store Review, you should be able to download it with the TestFlight app.
