### ISSUE TITLE
bug(android): sticky key previews 

### ISSUE THREAD

**Issue by Runeboard** [keymanapp/keyman#7510]
### Describe the bug

When typing keys either side of the spacebar within the Keyman app, those keys stay large after being released instead of returning to normal.

### Reproduce the bug

Please see the attached screen recording.
About the first 50 seconds is showing how it should work. After that is a combination of showing the problem and how the rest of the keyboard responds as it should in spite of that problem.

https://user-images.githubusercontent.com/115298797/197165746-a3394d98-69fd-4dec-86af-fcd756f6717a.mp4

### Expected behavior

Keys should not remained enlarged after being released. They should return to normal size.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

Keyman for Android 15.0

### Operating system

Android 11

### Device

Unihertz Jelly 2

### Keyboard name

Runeboard

### Keyboard version

1.0

### Language name

English (Runic)

**Comment by mcdurdin** [comment]
It's interesting that this appears to happen only on the bottom row. That may be significant.

**Comment by Runeboard** [comment]
> It's interesting that this appears to happen only on the bottom row. That may be significant.

Also, it's only happening in the Keyman app itself, not in other apps where the Keyman keyboard is used.

**Comment by darcywong00** [comment]
We've had a couple of fixes included in 16.0 for clearing popup and subkeys. We aim to release that in the upcoming months.

**Comment by mcdurdin** [comment]
You can try Keyman for Android v16 at https://keyman.com/alpha :grin:

**Comment by mcdurdin** [comment]
@MakaraSok or @bharanidharanj could you try and reproduce this on 15.0.271 and then, if you can repro, try again on latest 16.0.x alpha?

**Comment by darcywong00** [comment]
This should be fixed in 15.0.272 by #7554

**Comment by Runeboard** [comment]
> This should be fixed in 15.0.272 by #7554

I have version 15.0.273 on my phone and the problem is still present.

**Comment by mcdurdin** [comment]
@darcywong00 reopening for investigation

**Comment by bharanidharanj** [comment]
> @MakaraSok or @bharanidharanj could you try and reproduce this on 15.0.271 and then, if you can repro, try again on latest 16.0.x alpha?

@mcdurdin Okay, I will retest it.

**Comment by bharanidharanj** [comment]
@mcdurdin Retested this with 15.0.271 build as well as in the 16.0.92-alpha build in my Android Mobile device (ver 11) and here is my observation: 1. Not able to reproduce the above issue in both the Keyman Versions. ie., pressing any key (especially with the bottom row keys) in the Runeboard (English) keyboard did not stick with the enlarge size. Seems to be working fine in both the Keyman versions. Thanks.

**Comment by mcdurdin** [comment]
Thanks @bharanidharanj. It seems that there is still an issue here as @Runeboard is still experiencing it. @Runeboard do you have a consistent way to reproduce the problem?

**Comment by bharanidharanj** [comment]
@darcywong00 Retested this with Keyman 17.0.20-alpha build in my Android Mobile device Version 11.0 and I was not able to reproduce the same. ie., Keys are not remaine enlarged after being released. (especially from the bottom row of the keyboard) . Seems to be working fine in the latest Keyman alpha build too. Thanks.

**Comment by bharanidharanj** [comment]
@mcdurdin @darcywong00 Today, I was able to see the issue (ie., sticky key preview) in the Android 11 /  API 30 emulator. Here, What I did is:  1. I used the Keyman Keyboard as the System Keyboard and opened Chrome browser. 2. Tried to reproduce it in the browser. Suddenly, the Key preview stuck at one point. Closed the browser view. Restarted it. And tried to reproduce the same issue. But seems to be a random one. 

  
![keystuck](https://user-images.githubusercontent.com/19683143/210229390-fd4b0567-de08-4e62-882e-e09fd927f663.PNG)

**Comment by Runeboard** [comment]
> @mcdurdin @darcywong00 Today, I was able to see the issue (ie., sticky key preview) in the Android 11 / API 30 emulator. Here, What I did is: 1. I used the Keyman Keyboard as the System Keyboard and opened Chrome browser. 2. Tried to reproduce it in the browser. Suddenly, the Key preview stuck at one point. Closed the browser view. Restarted it. And tried to reproduce the same issue. Still, no luck.
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/19683143/210229390-fd4b0567-de08-4e62-882e-e09fd927f663.PNG">

This is interesting because I experience no problem in the Chrome browser at all. The sticking issue is never a problem there, nor is it a problem for any characters other than those either side of the spacebar.

A friend who uses an iPhone says it works fine for him and he does not have this problem.

**Comment by darcywong00** [comment]
I tried to repeat the key strokes from @Runeboard 's video.
I see at 0:48, he hits the shift button but the layer remains on default.
Then typing the <kbd>᛭</kbd> at 0:50 gets stuck.

But so far I haven't been able reproduce hitting the shift button and not have the layer change...

**Comment by Runeboard** [comment]
> I tried to repeat the key strokes from @Runeboard 's video. I see at 0:48, he hits the shift button but the layer remains on default. Then typing the ᛭ at 0:50 gets stuck.
> 
> But so far I haven't been able reproduce hitting the shift button and not have the layer change...

That bug has already been fixed.

**Comment by darcywong00** [comment]
@Runeboard - are you still experiencing this issue with Keyman for Android 16.0?

**Comment by Runeboard** [comment]
> @Runeboard - are you still experiencing this issue with Keyman for Android 16.0?

Yes, but not if I tap the key very quickly. It still occurs if I tap it at normal speed though.

**Comment by darcywong00** [comment]
> > @Runeboard - are you still experiencing this issue with Keyman for Android 16.0?
> 
> Yes, but not if I tap the key very quickly. It still occurs if I tap it at normal speed though.

Can you post another current video of the issue? We're still having difficulty in reproducing the issue.

**Comment by darcywong00** [comment]
Will defer to future (Waiting on external) until @Runeboard can update with a current video for us to reproduce the issue

**Comment by Runeboard** [comment]
As it's only happening in the Keyman app itself, but not when the keyboard is used in other apps, I no longer consider it a problem worth addressing. Thanks for caring about it but as an easy workaround solution exists anyway, I think it matters so little that it may as well be ignored.

**Comment by ermshiperete** [comment]
This can also happen with apps build by SAB or RAB because they use the keyboard in the same way. But so far we haven't heard any other reports of this bug and we can't reproduce it, so we leave it closed.
