### ISSUE TITLE
[Windows] Windows 10 keyboard name in settings

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#983]
With language pack installed in Windows 10, keyman keyboard name is not displayed under "Regions and Languages" settings. It is shown as "Unavailable input method"
![image](https://user-images.githubusercontent.com/14062593/41333937-363b1a72-6ea9-11e8-8ef0-ac3799637d3c.png)

Windows 7 is showing the Keyman keyboard name correctly.
![image](https://user-images.githubusercontent.com/14062593/41334294-b3edf3ee-6eaa-11e8-9cd8-cb6489ab47e0.png)

**Comment by mcdurdin** [comment]
See [Feedback Hub entry](https://aka.ms/AA2q36e); [How to send feedback to Microsoft for issues that impact Keyman](https://blog.keyman.com/2018/10/how-to-send-feedback-to-microsoft-for-issues-that-impact-keyman/)

**Comment by MayuraVerma** [comment]
done

**Comment by mcdurdin** [comment]
This has been fixed by Microsoft in Windows 10 1809. Tested here successfully.

**Comment by MayuraVerma** [comment]
Unfortunately, this is not fixed yet.

![image](https://user-images.githubusercontent.com/14062593/53216745-36a04200-361b-11e9-871a-5e0cc0a41cab.png)


![image](https://user-images.githubusercontent.com/14062593/53216794-59caf180-361b-11e9-91a6-6fabaec5f521.png)

With EuroLatin (SIL) keyboard
![image](https://user-images.githubusercontent.com/14062593/53216883-a1517d80-361b-11e9-9c1b-238bf093a9d0.png)

**Comment by mcdurdin** [comment]
I've just tested this with Windows 10 1903 (build #18875.1000) and can confirm it is working there. So looks like it wasn't in 1809 but perhaps in an intermediate update?

![image](https://user-images.githubusercontent.com/4498365/56338056-94dc4200-61d2-11e9-9e89-e0fc9691d6ee.png)

**Comment by MayuraVerma** [comment]
this is good. can we please check this with a keyboard name in unicode?

**Comment by mcdurdin** [comment]
![image](https://user-images.githubusercontent.com/4498365/56395960-f0f0a600-6266-11e9-8dc8-5236fef9895a.png)

**Comment by MayuraVerma** [comment]
Wonderful to see this.
It looks like this update will be rolled out all after June.
It is not listing the language name under the keyboard unlike the system keyboard.
Nonetheless, it's better than "Unavailable Input Method"

**Comment by MayuraVerma** [comment]
I confirm. This is resolved in Windows 10 May 2019 update, build 1903.
